### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by assasin541** [TeamMidnightDust/RoundTreesPack#3]
It doesn't work gor all type of logs, like acacia, full logs or else.

**Comment by Motschen** [comment]
Could you please be a little more descriptive than that? Which version of minecraft are you using, do you have any other resourcepacks, did you put Round Trees on top of all the other packs?

**Comment by assasin541** [comment]
@Motschen 1.16.3. I have other resourcepacks, better leaves is only above that.

**Comment by assasin541** [comment]
@Motschen with round trees only same problem. I'm talkig about full logs that has textures on every side.

**Comment by Motschen** [comment]
Oh, you mean bark blocks.
That's out of the scope of this resourcepack.
Old versions of the pack altered the bark blocks, but it was generally disliked, so I removed it.

**Comment by assasin541** [comment]
@Motschen that's understandable. So I think everything works, thanks! :)
